

export enum SessionState {
  NONE = "NONE",
  CREATING = 'CREATING',
  WAITING = 'WAITING',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  FINISHED = 'FINISHED',
  DESTROYED = 'DESTROYED',
  CANCELED = "CANCELED",
}